# Generated by Django 5.0.6 on 2024-07-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('teacher', '教師'), ('student', '生徒')], default='student', max_length=10),
        ),
    ]
