# Generated by Django 5.0.6 on 2024-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
