# Generated by Django 5.0.6 on 2024-07-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
