# Generated by Django 5.0.6 on 2024-08-01 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
